Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.synced_folder "./template_web", "/var/www/html"
  
  config.vm.provision "shell", inline: <<-SHELL
    which nginx || apt update && apt install -y nginx
    echo "<!-- Página servida desde Vagrant por Marce -->" >> /var/www/html/index.html
  SHELL
end



